### ISSUE TITLE
Make it work with custom fields?

### ISSUE THREAD

**Issue by Aetles** [Zodiac1978/tl-normalizer#1]
Hi, thanks for this time saving plugin! How much work would it be to support wysiwyg fields from ACF?

**Comment by Zodiac1978** [comment]
You can try adding this to the end of the plugin:
`add_filter('acf/update_value', 'tl_normalizer', 10, 1);`

This should add the filter on updating any ACF field.

Would you please test this and report back? This would be great.

**Comment by Zodiac1978** [comment]
Even better, you can do that just for WYSIWYG fields with this filter:
`add_filter('acf/update_value/type=wysiwyg', 'tl_normalizer', 10, 1);`
See: http://www.advancedcustomfields.com/resources/acfupdate_value/
